# -*- coding: utf-8 -*-
"""AlgoritmoElectricidad.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1grFgyTDKlUhzmkytkIajLafbtYFHGAmK
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

header = ['Refrigerator','Clothes washer', 'Clothes Iron', 'Computer', 'Oven', 'Play', 'TV', 'Sound system']
limites = {
    'Refrigerator': [3,300],
    'Clothes washer': [3,370],
    'Clothes Iron': [3,1100],
    'Computer': [3,62],
    'Oven': [3,1620],
    'Play': [3,70],
    'TV': [3, 70],
    'Sound system': [3,10]
}
promedio = {
    'Refrigerator': 135.77853225518456,
    'Clothes washer': 82.22966838986257,
    'Clothes Iron': 818.0531027466938,
    'Computer': 33.774209430032194,
    'Oven': 1314.0882119205298,
    'Play': 3.931849250047465,
    'TV': 63.701964037790795,
    'Sound system': 5.030001131605751
}
df_input = pd.read_csv('input_data.csv')

# Cargar el archivo CSV en un DataFrame
df = pd.read_csv('consumo_casa.csv')

valores = []

for head in header:
  # Definir el número límite
  # Crear un nuevo DataFrame con valores mayores que el límite en columna_x
  df_y = df.query(f'`{head}` >= {limites[head][0]}')[head]
  # Crear un nuevo DataFrame con valores mayores que el límite en columna_y
  df_x = df.query(f'`{head}` >= {limites[head][0]}')['MedidorW']

  # Calcular la pendiente (slope) e intercepto (intercept) de la línea de tendencia
  pendiente, intercepto = np.polyfit(df_x, df_y, 1)

  # Generar la línea de tendencia usando la ecuación y = mx + b
  linea_tendencia = pendiente * df_x + intercepto
  print(f"Ecuación de la recta de la línea de tendencia {head}: y = {pendiente}x + {intercepto}")
  # Aqui se ponen los datos del Medidor, la Matriz en dado caso
  for DatoMedidor in df_input['MedidorW']:
    valor = pendiente * DatoMedidor + intercepto
    if valor >= promedio[head]:
      valores.append(valor)
    else:
      valor = 0
      valores.append(valor)
    print(f"Valor {head}:", valor)